apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: ds1
  namespace: default
spec:
  datasources:
  - access: proxy
    editable: false
    isDefault: true
    jsonData:
      httpHeaderName1: "Authorization"
      timeInterval: 5s
    name: Prometheus
    secureJsonData:
      httpHeaderValue1: "Bearer kgedcgF_vNSSxvuKpKcWMhOZoljA88iGUbDslm8N4PQ" 
    type: prometheus
    url: https://prometheus-user-workload.openshift-user-workload-monitoring.svc.cluster.local:9091
    version: 1
  name: ds1.yaml
