---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-monitoring-grafana-datasource
  annotations:
  labels:
    app: grafana  
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: "openshift-monitoring-datasource"
      type: prometheus
      access: proxy
      url: https://prometheus-k8s.openshift-monitoring.svc:9091
      basicAuth: false
      withCredentials: false
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer SERVICE_SECRET" 
      editable: true
    - name: "custom-monitoring-datasource"
      type: prometheus
      access: proxy
      url: https://prometheus-user-workload.openshift-user-workload-monitoring.svc:9091
      basicAuth: false
      withCredentials: false
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer SERVICE_SECRET" 
      editable: true
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-monitoring-grafana-dashboard
  annotations:
  labels:
    app: grafana  
stringData:
  all.yml: |
    - name: 'default'       # name of this dashboard configuration (not dashboard itself)
      org_id: 1             # id of the org to hold the dashboard
      folder: ''            # name of the folder to put the dashboard (http://docs.grafana.org/v5.0/reference/dashboard_folders/)
      type: 'file'          # type of dashboard description (json files)
      options:
        folder: '/etc/grafana/provisioning/dashboards' 
  bios-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "panels": [
        {
          "content": "\n# Prometheus Demo\n\n* Custom python based prometheus exporter running on all nodes as a DaemonSet. Exports BIOS information\n* Custom Grafana instance and Dashboard to display the data\n\n\n",
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "gridPos": {
            "h": 4,
            "w": 11,
            "x": 0,
            "y": 0
          },
          "id": 4,
          "mode": "markdown",
          "timeFrom": null,
          "timeShift": null,
          "title": "Demo Description",
          "type": "text"
        },
        {
          "datasource": "custom-monitoring-datasource",
          "fieldConfig": {
            "defaults": {
              "custom": {
                "align": null,
                "displayMode": "json-view",
                "width": 150
              },
              "mappings": [
                {
                  "from": "",
                  "id": 0,
                  "operator": "",
                  "text": "",
                  "to": "",
                  "type": 1,
                  "value": "0"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "Misc"
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Time"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 166
                  },
                  {
                    "id": "custom.displayMode",
                    "value": "auto"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "node"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 395
                  },
                  {
                    "id": "displayName",
                    "value": "Node"
                  },
                  {
                    "id": "custom.displayMode",
                    "value": "auto"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "vendor"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 130
                  },
                  {
                    "id": "displayName",
                    "value": "Vendor"
                  },
                  {
                    "id": "custom.displayMode",
                    "value": "auto"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "version"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 70
                  },
                  {
                    "id": "displayName",
                    "value": "Version"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Value"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 59
                  },
                  {
                    "id": "displayName",
                    "value": "-"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "release_date"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 133
                  },
                  {
                    "id": "displayName",
                    "value": "Release Date"
                  },
                  {
                    "id": "custom.displayMode",
                    "value": "auto"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "bios_revision"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 106
                  },
                  {
                    "id": "displayName",
                    "value": "BIOS Revision"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "BIOS Revision"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 121
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Node"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 366
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "-"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 30
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 7,
            "w": 17,
            "x": 0,
            "y": 4
          },
          "id": 2,
          "options": {
            "showHeader": true
          },
          "pluginVersion": "7.0.0",
          "targets": [
            {
              "expr": "max(bios_info) by (node,bios_revision,release_date,vendor,version)",
              "format": "table",
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "BIOS Information",
          "type": "table"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 25,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "BIOS Information",
      "version": 14
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: grafana
  name: grafana
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    deployment: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 4
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
      deployment: grafana
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: grafana
        deployment: grafana
    spec:
      containers:
      - image: grafana/grafana:7.0.0
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: openshift-monitoring-grafana-datasource-volume
        - mountPath: /etc/grafana/provisioning/dashboards
          name: openshift-monitoring-grafana-dashboard-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: openshift-monitoring-grafana-datasource-volume
        secret:
          defaultMode: 420
          secretName: openshift-monitoring-grafana-datasource
      - name: openshift-monitoring-grafana-dashboard-volume
        secret:
          defaultMode: 420
          secretName: openshift-monitoring-grafana-dashboard
  triggers:
  - type: ConfigChange
