apiVersion: v1
kind: Secret
metadata:
  name: openshift-monitoring-grafana-datasource
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: "openshift-monitoring-datasource"
      type: prometheus
      access: proxy
      url: https://prometheus-k8s-openshift-monitoring.apps.cluster-swfts-c6ab.swfts-c6ab.sandbox1471.opentlc.com
      basicAuth: false
      withCredentials: false
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer SERVICE_SECRET" 
      editable: true
    - name: "custom-monitoring-datasource"
      type: prometheus
      access: proxy
      url: https://prometheus-user-workload.openshift-user-workload-monitoring.svc:9091
      basicAuth: false
      withCredentials: false
      isDefault: false
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer SERVICE_SECRET" 
      editable: true

